### ISSUE TITLE
Game Plan

### ISSUE THREAD

**Issue by roryclaasen** [GOGO98901/computing-project#9]
Space station is in the centre of the canvas. Enemy ships fly towards the the station in an attempt to destroy it.

## TODO
- [x] Add player (station)
- [x] Add enemy ships
- [x] Spawn questions when ready
- [x] Trig spaces ship paths and speed
- More will be added as time goes on

**Comment by roryclaasen** [comment]
- no longer ships but asteroids/metors
- not trig but vector math
  using [this question](http://gamedev.stackexchange.com/a/28337) as a pointer but I can't work out the normalisation parts (the code works however)
